---

exclude_paths:
  - test

detectors:
  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    public_methods_only: true

  ManualDispatch:
    exclude:
    - 'IletiMerkezi::Request#http'
