AllCops:
  Exclude:
    - 'iletimerkezisms.gemspec'
    - 'test/**/**'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/iletimerkezisms.rb'

Metrics/LineLength:
  Max: 100
