version: 2
jobs:
  build:
    working_directory: ~/ims
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          RACK_ENV: test

    steps:
      - checkout
      
      - restore_cache:
          keys:
            - iletimerkezi-bundle-{{ checksum "Gemfile.lock" }}
            - iletimerkezi-bundle-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: iletimerkezi-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Rubocop Check
          command: bundle exec rubocop

      - run:
          name: Test
          command: bundle exec rake test